all:
  stylesheets: [manifestation, manifestation-print: { media: all }]
  javascripts: [manifestation,duration]

showSuccess:
  stylesheets: [manifestation-view,view]
editSuccess:
  stylesheets: [manifestation-view,view]
newSuccess:
  stylesheets: [manifestation-view,view]
updateSuccess:
  stylesheets: [manifestation-view,view]
createSuccess:
  stylesheets: [manifestation-view,view]

templatingSuccess:
  stylesheets: [manifestation-templating.css,/sfFormExtraPlugin/css/jquery.autocompleter.css]
  javascripts: [/sfFormExtraPlugin/js/jquery.autocompleter.js, /cxFormExtraPlugin/js/cx_open_list.js]

listSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
