generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Picture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          picture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list: ~
      filter: ~
      form:    ~
      edit: ~
      new: ~
      show:
        display: [id]
