generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MemberCardPriceModel
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          member_card_price_model
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        member_card_type_id: { label: Type of member card }
        MemberCardType: { label: Type of member card }
        autoadd: { label: Added automatically, help: On the creation of a member card (online) }
        list_event: { label: Event }
      list:
        title: Prices association for member cards
        display: [name, Price, quantity, autoadd, _list_event, updated_at]
        table_method: retrieveList
        sort: [mct.name, desc]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [member_card_type_id, price_id, quantity, autoadd, event_id, updated_at]
      form:
        display: [member_card_type_id, price_id, quantity, autoadd, _form_meta_event_id, event_id]
      edit:    ~
      new:     ~
