generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EntryElement
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          entry_element
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        second_choice: { label: Needed }
      list:    ~
      filter:  ~
      form:
        display: [accepted,second_choice]
      edit:    ~
      new:     ~
