generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TitleType
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          title_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
      filter:
        display: [name]
      form:
        display: [name]
      edit:
        title: Title type "%%name%%"
      new:
        title: New title type
