generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MetaEvent
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          meta_event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_hide_in_month_calendars: { label: In calendars? }
        hide_in_month_calendars: { label: To be hidden in calendars? }
      list:
        display: [name, _list_hide_in_month_calendars]
        sort: [name,'']
      filter:  ~
      form:
        display:
          General: [name, hide_in_month_calendars]
          Users:   [users_list]
      edit:
        title: Edit Meta event "%%name%%"
      new:     ~
      show:
        display:
          General: [name]
