generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MetaEvent
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          meta_event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
        sort: [name,'']
      filter:  ~
      form:
        display:
          General: [name]
          Users:   [users_list]
      edit:
        title: Edit Meta event "%%name%%"
      new:     ~
      show:
        display:
          General: [name]
