generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Location
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          location
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _delete:
          credentials: [event-location-del]
        _new:
          credentials: [event-location-new]
        _edit:
          credentials: [event-location-edit]
        _manif_new:
          credentials: [event-manif-new]
      fields:
        Contact:      { label: Stage manager }
        contact_id:   { label: Stage manager }
        Organism:     { label: Organism }
        organism_id:  { label: Organism }
        gauge_max:    { label: Gauge max }
        gauge_min:    { label: Gauge min }
        reservation_price: { label: Costs, help: Reservation costs }
        rank:         { help: Number }
      list:
        display: [rank, name, postalcode, city, email, Contact, Organism, reservation_price]
        table_method: retrievePlaces
        object_actions:
          _show: ~
          _edit: ~
          _newManif:
            label: New Manifestation
            action: newManif
            params:
              onclick: return li_location_new_manif(this, "<?php sfApplicationConfiguration::getActive()->loadHelpers(array('I18N')); echo __("Are you sure?").'\n'.__("New transitional event's name:") ?>");
          _delete: ~
        sort: ['rank IS NULL, rank, name', '']
      filter:
        display: [name, postalcode, city, country, email, contact_id, organism_id, npai]
      form:
      edit:
        title: Editting location %%name%%
        display:
          General: [name, rank, email, contact_id, organism_id, reservation_price]
          Address: [address, postalcode, _cities, city, country, npai]
          More: [description, gauge_min, gauge_max]
          #Geolocalization: [_gmap]
      new:
        display:
          General: [name, rank, email, contact_id, organism_id, reservation_price]
          Address: [address, postalcode, _cities, city, country, npai]
          More: [description, gauge_min, gauge_max]
      show:
        display:
          General: [name, _show_email, _show_contact, _show_organism, _show_reservation_price]
          Address: [name, address, postalcode, city, country, npai]
          More:    [_show_description, gauge_min, gauge_max]
          #Geolocalization: [_gmap]
