generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Organism
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organism
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        name:       { label: Name }
        address:    { label: Address }
        postalcode: { label: Postal code }
        city:       { label: City }
        email:      { label: Email }
        list_email: { label: Email }
        npai:       { label: Has moved }
        country:    { label: Country }
        Category:   { label: Category }
        organism_category_id: { label: Category }
        created_at: { label: Created at }
        updated_at: { label: Updated at }
        description: { label: Description }
        url:        { label: URL }
        not_groups_list: { label: Not member of groups }
        email_no_newsletter: { label: No newsletter }
        email_newsletter: { label: Newsletter ? }
        groups_picto: { credentials: [pr-group], label: Remarkable }
        administrative_number: { label: Admin. ID }
        professional_meta_event_id: { label: Meta events }
      list:
        title: Organisms list
        display: [Category, name, postalcode, city, _list_email, administrative_number, _groups_picto, _contacts_list]
        max_per_page: 50
        object_actions:
          <?php if ( sfConfig::get('app_options_design',false) != 'tdp' ): echo PHP_EOL; ?>
          _show: ~
          <?php else: echo PHP_EOL; ?>
          _showUp:
            label: Show up
            action: edit
          <?php endif; echo PHP_EOL; ?>
          _edit: ~
          _delete: ~
        batch_actions:
          _delete: ~
          _addToGroup:
            label: Add in a group
          _merge: ~
        actions:
          _new: ~
          _extract:
            action: csv
            label: Extract to CSV
            credentials: pr-contact-csv
          _group:
            action: group
            label: Export to group
            credentials: [[pr-group-perso, pr-group-common]]
          _labels:
            action: labels
            label: Get labels
            credentials: pr-contact-label
      filter:
        display:
          Organism:   [name, postalcode, city, region_id, country, email, administrative_number, organism_category_id]
          Relations:  [contacts_groups, groups_list, not_groups_list]
          Communication: [npai <?php if ( !sfConfig::get('app_options_design',false) || !sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, email_newsletter<?php endif ?>, has_close_contact]
          Others:     [duplicates, professional_meta_event_id, email_no_newsletter]
      show:
        display:
          NONE: [name, address, postalcode, city, country, _show_region, _show_email, _show_phonenumbers_list, _show_url, Category, _show_groups_list]
          Details: [administrative_number, npai, description, created_at,updated_at,slug,longitude,latitude]
      form:
      edit:
        title: Organism %%name%%
        display:
          NONE:  [organism_category_id, name, address, postalcode, _cities, city, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_no_newsletter,<?php endif ?> url, groups_list]
          Phonenumbers: [_form_phonenumbers_list]
          Details: [administrative_number, npai, description]
      new:
        title: New organism
        display:
          NONE:  [organism_category_id, name, address, postalcode, _cities, city, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_no_newsletter,<?php endif ?> url]
          Phonenumbers: [phone_type,phone_number]
          Details: [administrative_number, npai, description]
