all:
  credentials: [tck-transaction]
cancelBoot:
  credentials: [tck-cancel]
cancel:
  credentials: [tck-cancel]
batchCancel:
  credentials: [tck-cancel]
cancelPartial:
  credentials: [tck-cancel]
print:
  credentials: [tck-print-ticket]
integrate:
  credentials: [tck-integrate]
batchIntegrate:
  credentials: [tck-integrate-foreign]
duplicate:
  credentials: [tck-print-ticket]
partial:
  credentials: [tck-print-ticket]
control:
  credentials: [tck-control]
controlCancel:
  credentials: [[tck-control<?php if ( !sfConfig::get('app_control_permissive', false) ): ?>, tck-control-admin<?php endif ?>]]
order:
  credentials: [tck-accounting-order]
invoice:
  credentials: [tck-accounting-invoice]
show:
  credentials: [tck-reports]
giveASeat:
  credentials: [tck-seat-allocation]
resetASeat:
  credentials: [tck-seat-allocation]
seatAllocation:
  credentials: [tck-seat-allocation]
