seated_plan:
  class: sfDoctrineRouteCollection
  options:
    model:                SeatedPlan
    module:               seated_plan
    prefix_path:          /seated_plan
    column:               id
    with_wildcard_routes: true

manifestation_pending:
  class: sfDoctrineRouteCollection
  options:
    model:                Manifestation
    module:               pending
    prefix_path:          /pending
    column:               id
    with_wildcard_routes: true

manifestation_conflict:
  class: sfDoctrineRouteCollection
  options:
    model:                Manifestation
    module:               conflict
    prefix_path:          /conflict
    column:               id
    with_wildcard_routes: true

vat:
  class: sfDoctrineRouteCollection
  options:
    model:                vat
    module:               vat
    prefix_path:          /vat
    column:               id
    with_wildcard_routes: true

workspace_user_ordering:
  class: sfDoctrineRouteCollection
  options:
    model:                WorkspaceUserOrdering
    module:               workspace_user_ordering
    prefix_path:          /workspace_user_ordering
    column:               id
    with_wildcard_routes: true

checkpoint:
  class: sfDoctrineRouteCollection
  options:
    model:                Checkpoint
    module:               checkpoint
    prefix_path:          /checkpoint
    column:               id
    with_wildcard_routes: true

price:
  class: sfDoctrineRouteCollection
  options:
    model:                Price
    module:               price
    prefix_path:          /price
    column:               id
    with_wildcard_routes: true

gauge:
  class: sfDoctrineRouteCollection
  options:
    model:                Gauge
    module:               gauge
    prefix_path:          /gauge
    column:               id
    with_wildcard_routes: true

price_manifestation:
  class: sfDoctrineRouteCollection
  options:
    model:                PriceManifestation
    module:               price_manifestation
    prefix_path:          /price_manifestation
    column:               id
    with_wildcard_routes: true

color:
  class: sfDoctrineRouteCollection
  options:
    model:                Color
    module:               color
    prefix_path:          /color
    column:               id
    with_wildcard_routes: true

calendar:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               calendar
    prefix_path:          /calendar
    column:               id
    with_wildcard_routes: true

meta_event:
  class: sfDoctrineRouteCollection
  options:
    model:                MetaEvent
    module:               meta_event
    prefix_path:          /meta_event
    column:               id
    with_wildcard_routes: true

event_category:
  class: sfDoctrineRouteCollection
  options:
    model:                EventCategory
    module:               event_category
    prefix_path:          /event_category
    column:               id
    with_wildcard_routes: true

resource:
  class: sfDoctrineRouteCollection
  options:
    model:                Location
    module:               resource
    prefix_path:          /resource
    column:               id
    with_wildcard_routes: true
location:
  class: sfDoctrineRouteCollection
  options:
    model:                Location
    module:               location
    prefix_path:          /location
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

manifestation:
  class: sfDoctrineRouteCollection
  options:
    model:                Manifestation
    module:               manifestation
    prefix_path:          /manifestation
    column:               id
    with_wildcard_routes: true

workspace:
  class: sfDoctrineRouteCollection
  options:
    model:                workspace
    module:               workspace
    prefix_path:          /workspace
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: event, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
