generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Professional
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          professional
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: Function }
        groups_picto: { label: Remarkable }
      list:
        display: [Contact, _groups_picto, name, Organism, contact_email]
        batch_actions: {}
        object_actions:
          _show: ~
          _edit:
            credentials: grp-events
        table_method: doSelectOnlyGrp
        title: By contact
      filter:
        display: [contact_name, organism_name, professional_type_id, organism_id, groups_list]
      form:    ~
      edit:
        actions: { _list: ~ }
      new:     ~
