all:
  javascripts: [/liTinymcePlugin/tiny_mce,email]
  stylesheets: [email]

contentSuccess:
  has_layout: false

indexSuccess:
  javascripts: [list-scroll]
  stylesheets: [list-print: {media: print}]

uploadSuccess:
  javascripts: [-/liTinymcePlugin/tiny_mce]
