<?php sfApplicationConfiguration::getActive()->loadHelpers(array('I18N')) ?>
all:
  transaction:
    display:
      simplified:
        simplified: ~
      intro:
        contact_id:
          class: board-alpha highlight
        professional_id:
          class: board-alpha highlight
        more:
          class: highlight
        description:
          class: board-alpha highlight
        informations:
          class: li_table highlight
        new_transaction: ~
      content:
        content: ~
        product_infos: ~
        board: ~
      payments:
        price_new: ~
        payment_new:
          class: highlight
        payments_list:
          class: highlight
          data_url: transaction/getPayments
      hidden:
        close: ~
    selling:
      manifestations:
        model: Manifestation
        title: <?php echo __('Manifestations').PHP_EOL ?>
        data_url: transaction/getManifestations
        choices_url: [event, manifestation/ajax]
      museum:
        model: Manifestation
        title: <?php echo __('Museum').PHP_EOL ?>
        data_url: transaction/getPeriods
        choices_url: [museum, manifestation/ajax]
        credentials: [tck-museum]
      store:
        model: Product
        title: <?php echo __('Store', null, 'menu').PHP_EOL ?>
        data_url: transaction/getStore
        choices_url: [pos, product/ajax]
        credentials: [tck-pos]
