#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Price:
  package: price
  actAs: [Timestampable]
  columns:
    name:
      type: string(63)
      notnull: true
      notblank: true
      unique: true
    description: string(255)
    value:
      type: decimal(8)
      scale: 2
      notnull: true
      default: 0
    online:
      type: boolean
      notnull: true
      default: false
    hide:
      type: boolean
      notnull: true
      default: false
    member_card_linked:
      type: boolean
      notnull: true
      default: false
  relations:
    Manifestations:
      class: Manifestation
      refClass: PriceManifestation
      foreignAlias: Prices
    Workspaces:
      class: Workspace
      refClass: WorkspacePrice
      foreignAlias: Prices
    Users:
      class: sfGuardUser
      refClass: UserPrice
      foreignAlias: Prices
      local: price_id
      foreign: sf_guard_user_id
    MemberCards:
      class: MemberCard
      refClass: MemberCardPrice
      foreignAlias: Prices
      local: price_id
      foreign: member_card_id

UserPrice:
  package: price
  columns:
    price_id:
      type: integer
      notnull: true
      primary: true
    sf_guard_user_id:
      type: integer
      notnull: true
      primary: true
  indexes:
    user_price_index:
      fields: [sf_guard_user_id, price_id]
      unique: true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: UserPrices
      onDelete: CASCADE
      onUpdate: CASCADE
    Price:
      foreignAlias: UserPrices
      onDelete: CASCADE
      onUpdate: CASCADE
      
      
WorkspacePrice:
  package: price
  columns:
    price_id:
      type: integer
      notnull: true
      primary: true
    workspace_id:
      type: integer
      notnull: true
      primary: true
  indexes:
    ws_price:
      fields: [workspace_id, price_id]
      unique: true
  relations:
    Workspace:
      foreignAlias: WorkspacePrices
      onDelete: CASCADE
      onUpdate: CASCADE
    Price:
      foreignAlias: WorkspacePrices
      onDelete: CASCADE
      onUpdate: CASCADE

PriceManifestation:
  package: price
  actAs: [Timestampable]
  columns:
    manifestation_id:
      type: integer
      notnull: true
    price_id:
      type: integer
      notnull: true
    value:
      type:  decimal(8)
      scale: 3
      notnull: true
  indexes:
    manif_price:
      fields: [manifestation_id, price_id]
      unique: true
  relations:
    Manifestation:
      foreignAlias: PriceManifestations
      onDelete: CASCADE
      onUpdate: CASCADE
    Price:
      foreignAlias: PriceManifestations
      onDelete: CASCADE
      onUpdate: CASCADE
