#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

AutoGroup:
  package: ws
  columns:
    group_id:
      type: integer
      notnull: true
  relations:
    Group:
      class: Group
      foreignAlias: Online
      onDelete: CASCADE
      onUpdate: CASCADE

RemoteAuthentication:
  package: ws
  actAs:
    Timestampable: ~
  indexes:
    remote_authentication_updated_at_idx:
      fields: [updated_at]
    user_ipaddress_idx:
      fields: [sf_guard_user_id, ipaddress]
      type: unique
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
    ipaddress:
      type: string(255)
      notnull: true
      notblank: true
    active:
      type: boolean
      notnull: true
      default: true
    salt:
      type: string(255)
      notnull: true
      notblank: true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Groups
      onDelete: CASCADE
      onUpdate: CASCADE

BankPayment:
  package: ws
  actAs:
    Timestampable: ~
  indexes:
    bank_payment_updated_at_idx:
      fields: [updated_at]
  columns:
    payment_id: integer
    serialized: string
    code: string(255)
    error: string
    merchant_id: string(255)
    merchant_country: string(255)
    amount: string(255)
    transaction_id: string(255)
    payment_means: string
    transmission_date: string(255)
    payment_time: string(255)
    payment_certificate: string(255)
    authorization_id: string(255)
    currency_code: string(255)
    card_number: string(255)
    cvv_flag: string(255)
    bank_response_code: string(255)
    complementary_code: string(255)
    complementary_info: string(255)
    return_context: string(255)
    caddie: string
    receipt_complement: string
    merchant_language: string(255)
    language: string(255)
    customer_id: string(255)
    order_id: string(255)
    customer_email: string(255)
    customer_ip_address: string(255)
    capture_day: string(255)
    capture_mode: string(255)
    data_field: string(255)
    cvv_response_code: string(255)
    payment_date: string(255)
    response_code: string(255)
    raw: string

Survey:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  actAs:
    Searchable:
      fields: [name, description]
    I18n:
      fields: [description]
  columns:
    name:
      type: string(255)
      notblank: true
      notnull: true
    description: string
    weight:
      type: integer
      notnull: true
      default: 100
SurveyQuery:
  package: ws
  actAs:
    I18n:
      fields: [name]
    Sluggable:
      fields: [name]
    Searchable:
      fields: [name]
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    name:
      type: string
      notblank: true
      notnull: true
    survey_id:
      type: integer
      notnull: true
    type:
      type: string(255)
      notnull: true
      notblank: true
    can_be_empty:
      type: boolean
      notnull: true
      default: true
    weight:
      type: integer
      notnull: true
      default: 100
    rank:
      type: integer
      notnull: true
      default: 0
    stats:
      type: enum
      values: [numbers, choices, free]
      default: free
      notnull: true
  relations:
    Survey:
      foreignAlias: Queries
      onDelete: CASCADE
      onUpdate: CASCADE
SurveyQueryOption:
  package: ws
  actAs:
    I18n:
      fields: [name]
  columns:
    survey_query_id:
      type: integer
      notnull: true
    name:
      type: string(255)
      notnull: true
      notblank: true
    value:
      type: string(255)
      notnull: true
  relations:
    Query:
      class: SurveyQuery
      foreignAlias: Options
      onDelete: CASCADE
      onUpdate: CASCADE
SurveyAnswer:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  actAs:
    Searchable:
      fields: [value]
  columns:
    survey_query_id:
      type: integer
      notnull: true
    survey_answers_group_id:
      type: integer
      notnull: true
    lang:
      type: string(255)
      notnull: true
      notblank: true
    value:
      type: string
      notnull: true
  relations:
    Query:
      class: SurveyQuery
      foreignAlias: Answers
      onDelete: RESTRICT
      onUpdate: CASCADE
    Group:
      class: SurveyAnswersGroup
      foreignAlias: Answers
      onDelete: CASCADE
      onUpdate: CASCADE
SurveyAnswersGroup:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    survey_id:
      type: integer
      notnull: true
    contact_id: integer
    professional_id: integer
    transaction_id: integer
  relations:
    Survey:
      foreignAlias: AnswersGroups
      onDelete: RESTRICT
      onUpdate: CASCADE
    Contact:
      foreignAlias: SurveyAnswersGroups
      onDelete: SET NULL
      onUpdate: CASCADE
    Professional:
      foreignAlias: SurveyAnswersGroups
      onDelete: SET NULL
      onUpdate: CASCADE
    Transaction:
      foreignAlias: SurveyAnswersGroups
      onDelete: SET NULL
      onUpdate: CASCADE
SurveyApplyTo:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    survey_id:
      type: integer
      notnull: true
    date_from: timestamp
    date_to: timestamp
    manifestation_id: integer
    group_id: integer
    contact_id: integer
    professional_id: integer
    organism_id: integer
    everywhere:
      type: boolean
      default: false
      notnull: true
  relations:
    Survey:
      foreignAlias: ApplyTo
      onDelete: CASCADE
      onUpdate: CASCADE
    Manifestation:
      foreignAlias: SurveysToApply
      onDelete: SET NULL
      onUpdate: CASCADE
    Group:
      foreignAlias: SurveysToApply
      onDelete: SET NULL
      onUpdate: CASCADE
    Contact:
      foreignAlias: SurveysToApply
      onDelete: SET NULL
      onUpdate: CASCADE
    Professional:
      foreignAlias: SurveysToApply
      onDelete: SET NULL
      onUpdate: CASCADE
    Organism:
      foreignAlias: SurveysToApply
      onDelete: SET NULL
      onUpdate: CASCADE

WebOrigin:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  indexes:
    web_origin_com_idx:
      fields: [campaign]
    web_origin_referer_idx:
      fields: [referer]
    web_origin_first_page_idx:
      fields: [first_page]
  columns:
    first_page:
      type: string
      notnull: true
    ipaddress:
      type: string(40)
      notnull: true
    referer: string
    campaign: string
    transaction_id:
      type: integer
      notnull: true
  relations:
    Transaction:
      foreignType: one
      onDelete: CASCADE
      onUpdate: CASCADE
