generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProfessionalType
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          professional_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
        object_actions:
          _edit: ~
          _delete: ~
        sort: [name, '']
      filter:
        display: [name]
      form:
        display: [name]
      edit:
        title: Professional type "%%name%%"
      new:
        title: New professional type
